wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
architecture:
  desc: null
  value: ppo
batch_size:
  desc: null
  value: 64
infra:
  desc: null
  value: Ubuntu
learning_rate:
  desc: null
  value: 0.0001
